FROM nvcr.io/nvidia/pytorch:21.07-py3

WORKDIR /app
ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0
RUN apk add --no-cache gcc musl-dev linux-headers

COPY ./app/requirements.prod.txt /app
RUN pip install --upgrade pip
RUN pip install -r /app/requirements.prod.txt

EXPOSE 5000
COPY . .

CMD [ "uwsgi", "--ini", "app.ini" ]